### PR TITLE
Version bump 2.1.7 and multiclusterhub rename

### PR DESCRIPTION
**Pull request by nathanweatherly**
https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/open-cluster-management/backlog/10938

### CODE REVIEW

**Review by JakobGray — CHANGES_REQUESTED** [review]
The chart files need to be updated to match the new version

**Comment by nathanweatherly** [comment]
Good catch Jake

**Review by JakobGray — APPROVED** [review]

**Pull request merged**
